version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "github-webhook-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-a39d51r32zvq"
s3_prefix = "github-webhook-service"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
