/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.webhook

import com.amazonaws.services.lambda.runtime.Context
import com.amazonaws.services.lambda.runtime.RequestHandler
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent
import com.google.gson.Gson

// TODO: (KevinMiller77) Remove these test classes

enum class Gender(val raw: Char) {
    MALE('M'),
    FEMALE('F'),
    WHATEVER_THE_FUCK('?')
}

data class Person (
    var name    : String,
    var age     : Int,
    var gender  : Gender
)
data class TheOnlyResponse (
    var hello     : String  = "Hello,",
    var world     : String  = "World!",
    var welcome   : String  = "to",
    var aws       : String  = "AWS",
    var lambda    : String  = "Lambda",
    var functions : String  = "Functions!",
    var num       : Int     = 69420,
    var float     : Float   = 420.69f,
    var bool      : Boolean = true,
    var p1        : Person  = Person("That dude", 57, Gender.MALE),
    var p2        : Person  = Person("Who?", 0, Gender.WHATEVER_THE_FUCK)
)

class LamdaHandler: RequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {
    override fun handleRequest(
        request: APIGatewayProxyRequestEvent, 
        context: Context
    ): APIGatewayProxyResponseEvent {
        var tor = TheOnlyResponse()

        val body = Gson().toJson(tor)

        println("Response body: \n\n")
        println(body)

        var response = APIGatewayProxyResponseEvent()
            .withStatusCode(200)
            .withBody(body)

        return response
    }
}
